---
- name: Create user using host scope variables
  hosts: 172.31.21.180
  tasks:
    - name: Create user
      user:
        name: "{{a}}"
        password: "{{b}}"
        uid: "{{c}}"
        home: "{{d}}"
        comment: "{{e}}"
        shell: "{{f}}"
