---
- name: Capture OS info of all managed nodes
  hosts: all
  tasks:
    - name: Capture OS info
      debug:
        msg: "{{ansible_distribution}}"
    - name: Capture OS version
      debug:
        msg: "{{ansible_distribution_version}}"
    - name: Capture OS major version
      debug:
        msg: "{{ansible_distribution_major_version}}"

