---
- name: Error Handling or Exception Handling
  hosts: all
  tasks:
    - block:
       - name: Install git using apt
         apt:
           name: git
           state: present
           update_cache: yes
      rescue:
       - name: Install git using yum
         yum:
           name: git
           state: present
           update_cache: yes
      always:
        - name: Print success msg
          debug:
            msg: "Git installation done"
