---
# handlers file for tomcat
- name: Check url respone
  uri:
    url: "{{item.a}}"
    status_code: "{{item.b}}"
  with_items:
    - {a: "{{server1}}",b: "{{status1}}"}
    - {a: "{{server2}}",b: "{{status1}}"}
